version: 2

models:
  - name: fact_manga_popularity
    description: "Fact table tổng hợp cho phân tích xu hướng nổi tiếng manga: rating, follows, chapters, tags, related series."
    columns:
      - name: manga_id
        description: "ID manga chính"
        tests:
          - unique
          - not_null
      - name: avg_rating
        description: "Rating trung bình"
        tests:
          - dbt_utils.accepted_range:
              arguments:
                column_name: avg_rating
                min_value: 0
                max_value: 10
      
    
      - name: status
        description: "Trạng thái manga"
        tests:
          - accepted_values:
              column_name: status
              values: ['ongoing', 'completed', 'hiatus', 'cancelled']
